name: Cron Sync

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  sync-manifests:
    name: Sync Manifests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        repository: winget-pkgs/manifests
        ssh-key: ${{ secrets.WINGET_MANIFESTS_DEPLOY_KEY }}
        ref: master
    - name: Sync Script
      run: |
        rm -r *
        svn export https://github.com/microsoft/winget-pkgs/trunk/manifests $(pwd) --force
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Updated: $(date -u +"%D %T %Z")" || true
        git push origin HEAD:master
