name: Cron Sync

on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  sync-manifests:
    name: Sync Manifests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        repository: winget-pkgs/manifests
        ssh-key: ${{ secrets.WINGET_MANIFESTS_DEPLOY_KEY }}
        ref: master
        path: 'destination'
    - name: Checkout microsoft/winget-pkgs
      uses: actions/checkout@v2
      with:
        repository: microsoft/winget-pkgs
        path: 'source'
    - name: Sync Script
      run: |
        cd destination
        rm -r *
        cp -r ../source/manifests/* .
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Updated: $(date -u +"%D %T %Z")" || true
        git push origin HEAD:master
